export const types = {

    authCheckingFinish: '[auth] Finish checking login state',
    authStartLogin: '[auth] Start login',
    authLogin: '[auth] Login',
    authStartRegister: '[auth] Start Register',
    authStartStartTokenRenew: '[auth] Start token renew',
    authLogout: '[auth] Logout',

    uiSetError: '[ui] Set Error',
    uiRemoveError: '[ui] Remove Error',
    uiStartLoading: '[ui] Start loading',
    uiFinishLoading: '[ui] Finish loading',
    uiSetOpenDrawer: '[ui] Set open drawer',
    uiSetCloseDrawer: '[ui] Set close drawer',
    uiSetChangePage: '[ui] Set change page',
    uiSetRowsPerPage: '[ui] Set rows per page',
    uiSetChangeDesde: '[ui] Set change desde',
    uiSetChangeDesdeSearch: '[ui] Set change desde search',
    uiSetChangeRowsPerPageSearch: '[ui] Set change rows per page search',
    uiShowPassword: '[ui] Show password',

    userStartGet: '[user] Start get usuario',
    userGet: '[user] Get usuarios',
    userStartUpdate: '[user] Start update usuario',
    userUpdate: '[user] Update usuario',
    userStartUploadFile: '[user] Start upload file',
    userUploadFile: '[user] Upload fifle',
    userClean: '[user] Clean reducer',

    modelStartLoading: '[model] Start loading',
    modelLoading: '[model] Loading',
    modelStartUpdate: '[model] Start update',
    modelUpdate: '[model] Update',
    modelStartDelete: '[model] Start delete',
    modelDelete: '[model] Delete',
    modelShowMore: '[model] Show more',
    modelSearchOn: '[model] Search models on',
    modelSearchOff: '[model] Search models off',
}